project:
  type: website
  output-dir: docs

website:
  title: "Introduction to MLE"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Contents"
        href: contents/binary_intro_binary.qmd
        
  sidebar: 
    - title: "Contents"    
      style: "docked"
      contents: 
        - section: "Binary responses"
          contents:
            - contents/binary_intro_binary.qmd
            - contents/binary_marginal_effects.qmd
            - contents/binary_substantive_effects.qmd
        - section: "3+ ordered responses"
          contents: 
            - contents/ordered_intro.qmd
            - contents/ordered_logistic.qmd
        - section: "3+ unordered responses"
          contents: 
            - contents/multinomial_intro.qmd
            - contents/multinomial_marginal_effects.qmd 
        - section: "Count responses"
          contents:
            - contents/count_intro.qmd
        - section: "Duration models"
          contents:
            - contents/event_intro.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

