project:
  type: website

website:
  title: "Introduction to MLE"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Contents"
        href: contents/index.qmd
        
  sidebar: 
    - title: "Contents"    
      style: "docked"
      contents: 
        - section: "Introduction"
          contents:
            - contents/index.qmd
        - section: "Binary responses"
          contents:
            - contents/binary_intro_binary.qmd
            - contents/binary_marginal_effects.qmd
            - contents/binary_substantive_effects.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

